### ISSUE TITLE
写了个demo遇到的了一些bug

### ISSUE THREAD

**Issue by JDongKhan** [mpflutter/mpflutter#127]
目前尝试写了个demo，遇到了一些问题，

环境如下：
```

name: mini_homepage
description: A new MPFlutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: "0.14.0"
  flutter_web_plugins: "0.14.0"
  mpcore: "0.14.0"
  mp_build_tools: "0.14.0"
dependency_overrides:
  flutter: "0.14.0"
  mpcore: "0.14.0"
  flutter_web_plugins: "0.14.0"

```

![Snip20220331_62](https://user-images.githubusercontent.com/4929805/160959771-8aa9aa8d-a95b-4a9a-8ab8-0b0a1fa54269.png)
![Snip20220331_61](https://user-images.githubusercontent.com/4929805/160959813-5257df06-7845-4896-8304-07dedd0e8f5e.png)
![Snip20220330_59](https://user-images.githubusercontent.com/4929805/160959866-03af146a-d73f-47d6-b60b-917f0812a8bc.png)

1、图1：图片和文字不是列布局而是居底了。
2、图2：倒是列布局了，但是顺序错乱了
3、图3：列表重叠了。
