### ISSUE TITLE
flutter 0.20.0 is incompatible with flutter_svg: ^1.1.4,

### ISSUE THREAD

**Issue by huang12zheng** [mpflutter/mpflutter#316]
[ ] flutter 0.20.0 is incompatible with flutter_svg: ^1.1.4,

* other:
[ ]`flutter_test at https://pub.mpflutter.com), version solving failed`

maybe the same as https://github.com/mpflutter/mpflutter/issues/95

I solve with
```
dependency_overrides:
  meta: ^1.7.0 # 必须添加这个依赖
  vector_math: ^2.1.2
  collection: ^1.17.0
```
and run `flutter pub get`

So, Is this a reasonable approach?
