### ISSUE TITLE
模板的依赖包是最新的吗？

### ISSUE THREAD

**Issue by dong-lufei** [mpflutter/mpflutter#332]
依赖包是最新的吗？
```
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: "1.0.0"
  flutter_web_plugins: "1.0.0"
```

如何升级依赖包版本，是 flutter pub outdated ？
