### ISSUE TITLE
自定义字体没有生效

### ISSUE THREAD

**Issue by qinrunhao** [mpflutter/mpflutter#598]
你好，我的应用中有自定义字体，字体放在根目录fonts下，pubspec.yaml的配置如下，其中FlutterRemix是自定义字体，应用运行在安卓上，能正确显示字体，但编译成小程序后无法显示，请问这个问题怎么解决呢？
```
flutter:
  uses-material-design: true
  fonts:
    - family: FlutterRemix
      fonts:
        - asset: fonts/FlutterRemix.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Noto Sans SC
      fonts:
        - asset: fonts/NotoSansSC-Regular.ttf
```
