### ISSUE TITLE
构建微信小程序失败

### ISSUE THREAD

**Issue by LondonX** [mpflutter/mpflutter#84]
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (8 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

flutter: "0.12.1"
flutter_web_plugins: "0.12.1"
mpcore: "0.12.1"
mp_build_tools: "0.12.1"

执行`dart scripts/build_weapp.dart`时报错
```
../../Library/flutter/.pub-cache/hosted/pub.mpflutter.com/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
```
猜测是flutter 2.5后删除了`io.Platform.packageRoot`属性。相关文档[Deprecated API removed after v2.5](https://flutter.cn/docs/release/breaking-changes/2-5-deprecations#packageroot-in-dartcore-dartisolate-and-packageplatform)。
目前的方案是将`local_platform.dart`中的
``` dart
String? get packageRoot => io.Platform.packageRoot;
```
修改为
``` dart
String? get packageRoot => null;
```

**Comment by PonyCui** [comment]
是未经过修改 mpflutter_template 代码吗？

**Comment by LondonX** [comment]
用到了json_serializable和build_runner，但目前测试没有问题。
pubspec.yaml如下
``` yaml
name: mpflutter_template
description: A new MPFlutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: "0.12.1"
  flutter_web_plugins: "0.12.1"
  mpcore: "0.12.1"
  mp_build_tools: "0.12.1"
  path_provider: ^2.0.7
  universal_miniprogram_api:
  json_annotation:
  http:
  intl: ^0.17.0
  shared_preferences:
  uuid: ^3.0.5
dev_dependencies:
  build_runner:
  json_serializable:
dependency_overrides:
  flutter: "0.12.1"
  mpcore: "0.12.1"
  flutter_web_plugins: "0.12.1"
flutter:
  assets:
    - assets/images/
```
